version: '3'
services:
  apache:
    build: .
    image: wol
    container_name: wol
    hostname: wol
    environment:
      - wakeonlan=wakeonlan -i 192.168.1.1 xx:xx:xx:xx:xx:xx
      - ping=ping -c 1 192.168.1.1
    volumes:
      - ./www:/var/www
    ports:
      - "8080:80"
