version: '3'
services:
  apache:
    build: .
    image: wol
    container_name: wol
    hostname: wol
    environment:
      ip_address=192.168.1.1 # ここにIPアドレスを記述
      mac_address=XX:XX:XX:XX:XX:XX # ここにMACアドレスを記述
    volumes:
      - ./www:/var/www
    ports:  
      - "8080:80"
